url: https://athenafoster.com
baseurl: ""

# Site settings
title: AthenaFoster.com
email: athena@athenafoster.com
description: "Athena Foster, freelance writer."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/AthenaFoster
    text: Find me on Facebook
  - title: goodreads
    url: https://www.goodreads.com/athenafoster
    text: What I'm reading
  - title: spotify
    url: https://open.spotify.com/user/1255770321?si=a6cb666720424455&nd=1
    text: What I'm listening to
  - title: twitter
    url: https://twitter.com/PedanticASF
    text: Follow me on Twitter
  - title: github
    url: https://github.com/AthenaFoster
    text: My GitHub profile

works:
- title: Sown Men
  subtitle: Paradise Icon Anthology 2020
  img: paradise-icon-anthology-2020.jpg
  url: https://amazon.com/Paradise-Icon-Anthology-2020-Schaff-Stump-ebook/dp/B09F8D2JX6
- title: Title B
  subtitle: Paradise Icon Anthology 2020
  img: paradise-icon-anthology-2020.jpg
  url: https://amazon.com/Paradise-Icon-Anthology-2020-Schaff-Stump-ebook/dp/B09F8D2JX6
- title: Title C
  subtitle: Paradise Icon Anthology 2020
  img: paradise-icon-anthology-2020.jpg
  url: https://amazon.com/Paradise-Icon-Anthology-2020-Schaff-Stump-ebook/dp/B09F8D2JX6
- title: Title D
  subtitle: Paradise Icon Anthology 2020
  img: paradise-icon-anthology-2020.jpg
  url: https://amazon.com/Paradise-Icon-Anthology-2020-Schaff-Stump-ebook/dp/B09F8D2JX6
- title: Title E
  subtitle: Paradise Icon Anthology 2020
  img: paradise-icon-anthology-2020.jpg
  url: https://amazon.com/Paradise-Icon-Anthology-2020-Schaff-Stump-ebook/dp/B09F8D2JX6
- title: Title F
  subtitle: Paradise Icon Anthology 2020
  img: paradise-icon-anthology-2020.jpg
  url: https://amazon.com/Paradise-Icon-Anthology-2020-Schaff-Stump-ebook/dp/B09F8D2JX6

# Team names, titles and social links
people:
- name: Athena Foster
  pic: athena
  position: Writer

# Postal address (add as many lines as necessary)
address:
  - line: Madison, WI

# Build settings
markdown: kramdown
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: "" # NB: all files in the project
    values:
      layout: page
