url: https://athenafoster.com
baseurl: ""

# Site settings
title: AthenaFoster.com
email: athena@athenafoster.com
description: "Athena Foster, freelance writer."

# Team names, titles and social links
people:
- name: Athena Foster
  pic: athena
  position: Writer
  social:
    - title: facebook
      url: https://facebook.com/AthenaFoster
    - title: goodreads
      url: https://www.goodreads.com/athenafoster
    - title: spotify
      url: https://www.spotify.com/
    - title: twitter
      url: https://twitter.com/PedanticASF
    - title: github
      url: https://github.com/AthenaFoster

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/PedanticASF
  - title: github
    url: http://github.com/AthenaFoster

# Postal address (add as many lines as necessary)
address:
  - line: Madison, WI

# Build settings
markdown: kramdown
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: "" # NB: all files in the project
    values:
      layout: page
